services:
  postgresql:
    image: postgres:15.3
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_ROOT_USER:?}"
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD:?}"
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgresql_data:
